const ARCHIVE = [
  {
    id: 1,
    src: "images/archive-photos/p01-opening-namaste-mahacharya-reena-rinku-minister.jpg",
    category: "stage",
    en: "A namaste opens the conversation that will place the Krishi Ratna League before Bengal.",
    bn: "নমস্কারে শুরু সেই কথোপকথন, যা বাংলার সামনে কৃষি রত্ন লীগকে তুলে ধরবে।",
  },
  {
    id: 2,
    src: "images/archive-photos/p02-opening-wide-rinku-minister-on-stage.jpg",
    category: "stage",
    en: "Opening wide. Rinku and Minister on bamboo seats. Welcome banner on screen.",
    bn: "স্বাগত ব্যানারের সামনে মঞ্চে রিঙ্কু ও কৃষিমন্ত্রী।",
  },
  {
    id: 3,
    src: "images/archive-photos/p03-rinku-and-minister-seated-close.jpg",
    category: "people",
    en: "Smt. Rinku Majumder Ghosh and Shri Dudh Kumar Mondal, seated.",
    bn: "পাশাপাশি আসনে শ্রীমতি রিঙ্কু মজুমদার ঘোষ ও শ্রী দুধ কুমার মণ্ডল।",
  },
  {
    id: 4,
    src: "images/archive-photos/p04-rinku-majumder-ghosh-portrait.jpg",
    category: "people",
    en: "Smt. Rinku Majumder Ghosh, whose acceptance address placed women farmers at the heart of the League.",
    bn: "শ্রীমতী রিঙ্কু মজুমদার ঘোষ, যাঁর দায়িত্ব গ্রহণের ভাষণে লীগের কেন্দ্রে উঠে এলেন নারী কৃষকেরা।",
  },
  {
    id: 5,
    src: "images/archive-photos/p05-mahacharya-speaking-rinku-minister-listen.jpg",
    category: "people",
    en: "MahAcharyaJi at the lectern. Rinku and Minister listening.",
    bn: "মহাচার্যজির বক্তব্য শুনছেন রিঙ্কু ও কৃষিমন্ত্রী।",
  },
  {
    id: 6,
    src: "images/archive-photos/p06-rinku-and-minister-on-stage.jpg",
    category: "people",
    en: "Rinku and Minister on stage against the welcome banner.",
    bn: "স্বাগত ব্যানারের সামনে রিঙ্কু ও কৃষিমন্ত্রী।",
  },
  {
    id: 7,
    src: "images/archive-photos/p07-minister-dudh-kumar-mondal-seated.jpg",
    category: "people",
    en: "Shri Dudh Kumar Mondal, Hon'ble Minister of Agriculture, WB. Seated.",
    bn: "মঞ্চে শ্রী দুধ কুমার মণ্ডল।",
  },
  {
    id: 8,
    src: "images/archive-photos/p08-minister-dudh-kumar-mondal-portrait.jpg",
    category: "people",
    en: "Minister Mondal, portrait.",
    bn: "শ্রী দুধ কুমার মণ্ডলের প্রতিকৃতি।",
  },
  {
    id: 9,
    src: "images/archive-photos/p09-mahacharya-at-lectern-minister-listening.jpg",
    category: "people",
    en: "MahAcharyaJi speaking. Minister listening from the bamboo chair.",
    bn: "বাঁশের আসনে কৃষিমন্ত্রী, বেদিতে মহাচার্যজি।",
  },
  {
    id: 10,
    src: "images/archive-photos/p10-mahacharya-at-lectern-minister-profile.jpg",
    category: "people",
    en: "MahAcharyaJi at lectern, palms together. Minister in profile.",
    bn: "বেদিতে নমস্কার জানাচ্ছেন মহাচার্যজি।",
  },
  {
    id: 11,
    src: "images/archive-photos/p11-green-room-minister-offered-tea.jpg",
    category: "people",
    en: "Green room. Minister offered clay-cup tea by the team.",
    bn: "গ্রিন রুমে মাটির কাপে কৃষিমন্ত্রীকে চা পরিবেশন।",
  },
  {
    id: 12,
    src: "images/archive-photos/p12-green-room-minister-with-phone.jpg",
    category: "people",
    en: "Green room. Minister with phone.",
    bn: "গ্রিন রুমে ফোন হাতে কৃষিমন্ত্রী।",
  },
  {
    id: 13,
    src: "images/archive-photos/p13-green-room-minister-mirror.jpg",
    category: "people",
    en: "Green room. Minister, mirror, waiting room.",
    bn: "অনুষ্ঠানের আগে গ্রিন রুমে কৃষিমন্ত্রী।",
  },
  {
    id: 14,
    src: "images/archive-photos/p14-mahacharya-from-behind-krl-slide.jpg",
    category: "stage",
    en: "MahAcharyaJi from behind at the lectern. Laptop on KarmYog/BKS slide 3 of 17.",
    bn: "বেদির পেছন থেকে দেখা মঞ্চ। ল্যাপটপে কর্মযোগ ও ভারতীয় কৃষক সমাজ।",
  },
  {
    id: 15,
    src: "images/archive-photos/p15-reena-rinku-dhar-on-stage-krl-mark.jpg",
    category: "people",
    en: "Reena, Rinku (badge), Dhar on stage. KRL mark on screen.",
    bn: "পর্দায় কৃষি রত্ন লীগের চিহ্ন, মঞ্চে রীনা, রিঙ্কু ও দেবাশীষ ধর।",
  },
  {
    id: 16,
    src: "images/archive-photos/p16-reena-rinku-dhar-seated.jpg",
    category: "people",
    en: "Smt. Reena J. Sarkar, Smt. Rinku Majumder Ghosh, Shri Debashish Dhar.",
    bn: "শ্রীমতি রীনা জে. সরকার, শ্রীমতি রিঙ্কু মজুমদার ঘোষ ও শ্রী দেবাশীষ ধর।",
  },
  {
    id: 17,
    src: "images/archive-photos/p17-reena-rinku-dhar-listening.jpg",
    category: "people",
    en: "The three listening. Rinku wearing the Mahila Wing badge.",
    bn: "মঞ্চে মন দিয়ে শুনছেন অতিথিরা।",
  },
  {
    id: 18,
    src: "images/archive-photos/p18-reena-rinku-dhar-three-shot.jpg",
    category: "people",
    en: "Three-shot. Reena, Rinku, Dhar.",
    bn: "এক ফ্রেমে রীনা, রিঙ্কু ও দেবাশীষ ধর।",
  },
  {
    id: 19,
    src: "images/archive-photos/p19-dhar-green-room-portrait.jpg",
    category: "people",
    en: "Shri Debashish Dhar, MLA Sonarpur Uttar. Green room.",
    bn: "গ্রিন রুমে শ্রী দেবাশীষ ধর।",
  },
  {
    id: 20,
    src: "images/archive-photos/p20-dhar-green-room-with-phone.jpg",
    category: "people",
    en: "Dhar in green room with phone.",
    bn: "গ্রিন রুমে ফোন হাতে দেবাশীষ ধর।",
  },
  {
    id: 21,
    src: "images/archive-photos/p21-dhar-at-okakura-gate.jpg",
    category: "people",
    en: "Dhar at the Okakura gate, with security.",
    bn: "রবীন্দ্র ওকাকুরা ভবনের প্রবেশদ্বারে দেবাশীষ ধর।",
  },
  {
    id: 22,
    src: "images/archive-photos/p22-dhar-at-okakura-gate-adjusting-uttariya.jpg",
    category: "people",
    en: "Dhar at the gate, adjusting uttariya.",
    bn: "প্রবেশদ্বারে উত্তরীয় ঠিক করছেন দেবাশীষ ধর।",
  },
  {
    id: 23,
    src: "images/archive-photos/p23-dhar-received-on-stage-felicitation-slide.jpg",
    category: "people",
    en: "Dhar received on stage. Felicitation of Rinku on the screen behind.",
    bn: "মঞ্চে দেবাশীষ ধরকে অভ্যর্থনা।",
  },
  {
    id: 24,
    src: "images/archive-photos/p24-mahacharya-speaking-reena-rinku-dhar-listen.jpg",
    category: "stage",
    en: "MahAcharyaJi speaking. Reena, Rinku, Dhar seated.",
    bn: "মহাচার্যজির বক্তব্য শুনছেন রীনা, রিঙ্কু ও দেবাশীষ ধর।",
  },
  {
    id: 25,
    src: "images/archive-photos/p25-from-stage-looking-into-the-hall.jpg",
    category: "people",
    en: "From the stage into the hall. MahAcharyaJi at lectern.",
    bn: "মঞ্চ থেকে দর্শকাসনের দিকে।",
  },
  {
    id: 26,
    src: "images/archive-photos/p26-hero-mahacharya-addressing-the-full-hall.jpg",
    category: "people",
    en: "MahAcharya Shri Sourabh J. Sarkar addressing the hall.",
    bn: "হলকে সম্বোধন করছেন মহাচার্য শ্রী সৌরভ জে. সরকার।",
  },
  {
    id: 27,
    src: "images/archive-photos/p27-stage-with-krl-mark-on-screen.jpg",
    category: "stage",
    en: "Stage with KRL farmer-mark on the right screen.",
    bn: "পর্দায় কৃষি রত্ন লীগের চিহ্ন।",
  },
  {
    id: 28,
    src: "images/archive-photos/p28-sacred-bell-felicitation-standing-four.jpg",
    category: "stage",
    en: "The bell that opened the morning. Moments later, Smt. Rinku Majumder Ghosh was felicitated as Adhyakshaa of the Mahila Wing.",
    bn: "যে ঘণ্টাধ্বনিতে সকালের সূচনা। কিছু পরেই মহিলা শাখার অধ্যক্ষা হিসেবে সংবর্ধিত হন শ্রীমতী রিঙ্কু মজুমদার ঘোষ।",
  },
  {
    id: 29,
    src: "images/archive-photos/p29-wide-krl-bengal-launch-slide.jpg",
    category: "stage",
    en: "Wide. Launch of Krishi Ratna League Bengal on screen.",
    bn: "পর্দায় কৃষি রত্ন লীগ বাংলার উদ্বোধন।",
  },
  {
    id: 30,
    src: "images/archive-photos/p30-dhar-speaking-at-lectern.jpg",
    category: "people",
    en: "The Guest of Honour's address: Shri Debashish Dhar brings the voice of Sonarpur Uttar to the convening.",
    bn: "বিশেষ অতিথির ভাষণে সম্মেলনে সোনারপুর উত্তরের প্রতিনিধিত্ব করছেন শ্রী দেবাশীষ ধর।",
  },
  {
    id: 31,
    src: "images/archive-photos/p31-dhar-at-lectern-portrait.jpg",
    category: "people",
    en: "Dhar at the lectern. Portrait. KarmYog wordmark behind.",
    bn: "বেদিতে শ্রী দেবাশীষ ধর।",
  },
  {
    id: 32,
    src: "images/archive-photos/p32-dhar-speaking-mahacharya-reena-listen.jpg",
    category: "people",
    en: "Dhar speaking. MahAcharyaJi and Reena listening.",
    bn: "দেবাশীষ ধরের বক্তব্য শুনছেন মহাচার্যজি ও রীনা।",
  },
  {
    id: 33,
    src: "images/archive-photos/p33-reena-j-sarkar-listening.jpg",
    category: "people",
    en: "Smt. Reena J. Sarkar listening. Yellow sari.",
    bn: "মন দিয়ে শুনছেন শ্রীমতি রীনা জে. সরকার।",
  },
  {
    id: 34,
    src: "images/archive-photos/p34-the-hall-audience-wide.jpg",
    category: "people",
    en: "The hall. Press, farmers, team.",
    bn: "হলে সংবাদমাধ্যম, কৃষক ও আয়োজকেরা।",
  },
  {
    id: 35,
    src: "images/archive-photos/p35-the-hall-audience-front-rows.jpg",
    category: "people",
    en: "The audience for a new beginning in Bengal's agriculture, listening from the front rows.",
    bn: "বাংলার কৃষিতে নতুন সূচনার কথা শুনছেন সামনের সারির শ্রোতারা।",
  },
  {
    id: 36,
    src: "images/archive-photos/p36-press-huddle-mahacharya-back-to-cameras.jpg",
    category: "press",
    en: "The announcement becomes a conversation: journalists gather around MahAcharya Shri Sourabh J. Sarkar with their questions.",
    bn: "ঘোষণা থেকে কথোপকথন: প্রশ্ন নিয়ে মহাচার্য শ্রী সৌরভ জে. সরকারকে ঘিরে ধরেছেন সাংবাদিকেরা।",
  },
  {
    id: 37,
    src: "images/archive-photos/p37-press-huddle-mahacharya-hands-raised.jpg",
    category: "press",
    en: "Press huddle. MahAcharyaJi speaking, hands raised.",
    bn: "সংবাদমাধ্যমের সঙ্গে কথোপকথন।",
  },
  {
    id: 38,
    src: "images/archive-photos/p38-press-huddle-from-stage-right.jpg",
    category: "press",
    en: "Press huddle from stage right. Reena seated, cameras in.",
    bn: "মঞ্চের ডান দিক থেকে সংবাদমাধ্যমের সমাবেশ।",
  },
  {
    id: 39,
    src: "images/archive-photos/p39-press-huddle-variant.jpg",
    category: "press",
    en: "A conversation with the press, beside the stage.",
    bn: "মঞ্চের পাশে সংবাদমাধ্যমের ভিড়।",
  },
  {
    id: 40,
    src: "images/archive-photos/p40-press-huddle-variant-dup-of-p46.jpg",
    category: "press",
    en: "A close-up from the press gathering.",
    bn: "প্রেসের সঙ্গে কথোপকথনের একটি মুহূর্ত।",
  },
  {
    id: 41,
    src: "images/archive-photos/p41-press-mahacharya-rinku-dhar-bonglive-mic.jpg",
    category: "press",
    en: "Press. MahAcharyaJi, Rinku, Dhar. Bonglive mic in frame.",
    bn: "সংবাদমাধ্যমের সামনে মহাচার্যজি, রিঙ্কু ও দেবাশীষ ধর।",
  },
  {
    id: 42,
    src: "images/archive-photos/p42-press-mahacharya-rinku-dhar-close.jpg",
    category: "press",
    en: "Press close. MahAcharyaJi speaking. Rinku. Dhar. Mics.",
    bn: "কাছ থেকে দেখা প্রেসের সঙ্গে কথোপকথন।",
  },
  {
    id: 43,
    src: "images/archive-photos/p43-press-conference-variant.jpg",
    category: "press",
    en: "Guests in conversation with the press.",
    bn: "সংবাদমাধ্যমের মুখোমুখি অতিথিরা।",
  },
  {
    id: 44,
    src: "images/archive-photos/p44-press-conference-variant.jpg",
    category: "press",
    en: "Questions from the press, answers from the stage.",
    bn: "প্রেসের প্রশ্ন, অতিথিদের উত্তর।",
  },
  {
    id: 45,
    src: "images/archive-photos/p45-press-dhar-speaking-to-mics.jpg",
    category: "press",
    en: "Dhar speaking into a ring of mics. 24 Ghanta visible.",
    bn: "মাইক্রোফোনের সামনে বক্তব্য রাখছেন দেবাশীষ ধর।",
  },
  {
    id: 47,
    src: "images/archive-photos/p47-press-conference-wide-full-stage.jpg",
    category: "press",
    en: "Press conference wide. Full stage, team standing behind.",
    bn: "পুরো মঞ্চ জুড়ে সংবাদমাধ্যম ও আয়োজকেরা।",
  },
  {
    id: 48,
    src: "images/archive-photos/p48-closing-flowers-minister-rinku-reena.jpg",
    category: "people",
    en: "Flowers and a moment of recognition on stage.",
    bn: "মঞ্চে ফুল দিয়ে শুভেচ্ছা জানানোর মুহূর্ত।",
  },
  {
    id: 49,
    src: "images/archive-photos/p49-closing-variant.jpg",
    category: "stage",
    en: "Protyabartan is unveiled — the Durga Puja trilogy that will bring an integrated farm to the pandal ground.",
    bn: "উন্মোচিত হল ‘প্রত্যাবর্তন’ — দুর্গাপূজার সেই ত্রয়ী, যার মণ্ডপ প্রাঙ্গণে গড়ে উঠবে সমন্বিত খামার।",
  },
  {
    id: 50,
    src: "images/archive-photos/p50-press-panel-seated-from-left.jpg",
    category: "press",
    en: "Press panel from the left. Team standing behind the sofa.",
    bn: "মঞ্চে বসে সংবাদমাধ্যমের সঙ্গে কথোপকথন।",
  },
  {
    id: 51,
    src: "images/archive-photos/p51-closing-or-press-variant.jpg",
    category: "people",
    en: "Cameras and microphones gather around the stage.",
    bn: "মঞ্চ ঘিরে ক্যামেরা ও মাইক্রোফোন।",
  },
  {
    id: 52,
    src: "images/archive-photos/p52-closing-or-press-variant.jpg",
    category: "people",
    en: "Taking questions from the media.",
    bn: "সংবাদমাধ্যমের প্রশ্ন নিচ্ছেন অতিথিরা।",
  },
  {
    id: 53,
    src: "images/archive-photos/p53-closing-or-press-variant.jpg",
    category: "people",
    en: "The conversation continues with the press.",
    bn: "সংবাদমাধ্যমের সঙ্গে শেষ পর্যায়ের কথোপকথন।",
  },
  {
    id: 54,
    src: "images/archive-photos/p54-rinku-garlands-dhar-on-stage.jpg",
    category: "people",
    en: "Rinku garlands Dhar. Reena watching. MahAcharyaJi with the bell. Hall photographing.",
    bn: "শ্রী দেবাশীষ ধরকে মালা পরাচ্ছেন শ্রীমতি রিঙ্কু মজুমদার ঘোষ।",
  },
  {
    id: 55,
    src: "images/archive-photos/p55-outside-okakura-group-at-gate.jpg",
    category: "people",
    en: "Outside Rabindra Okakura Bhawan, the gathering comes together beneath the Protyabartan banners after the morning's announcements.",
    bn: "সকালের ঘোষণার পরে রবীন্দ্র ওকাকুরা ভবনের বাইরে প্রত্যাবর্তনের ব্যানারের নীচে সমবেত অতিথিরা।",
  },
  {
    id: 57,
    src: "images/archive-photos/p57-closing-variant.jpg",
    category: "people",
    en: "A moment of recognition on stage.",
    bn: "মঞ্চে অতিথিদের সম্মাননা।",
  },
  {
    id: 58,
    src: "images/archive-photos/p58-closing-variant.jpg",
    category: "people",
    en: "The screen introduces Partha S. Chatterjee's video testimonial.",
    bn: "পর্দায় পার্থ এস. চ্যাটার্জির ভিডিও সাক্ষ্যচিত্রের পরিচয়।",
  },
  {
    id: 59,
    src: "images/archive-photos/p59-closing-variant.jpg",
    category: "people",
    en: "A moment beneath the welcome banner.",
    bn: "স্বাগত ব্যানারের সামনে একটি মুহূর্ত।",
  },
  {
    id: 60,
    src: "images/archive-photos/p60-press-panel-seated-canonical.jpg",
    category: "press",
    en: "The guests and organisers, together with the press.",
    bn: "সংবাদমাধ্যমের সঙ্গে আলোচনায় অতিথি ও আয়োজকেরা।",
  },
];
