const T = {
  en: {
    navDay: "The day",
    navGallery: "Gallery",
    navPress: "Press",
    navMedia: "Media",
    brand: "Media Connect",
    heroKicker: "14 September 2026",
    heroTitle: "Protyabartan",
    heroSub:
      "A Media Connect at Rabindra Okakura Bhawan. Krishi Ratna League Bengal begins.",
    fDate: "Date",
    fDateV: "Monday, 14 September 2026",
    fPlace: "Venue",
    fPlaceV: "Rabindra Okakura Bhawan, DD Block, Salt Lake, Kolkata",
    fTheme: "Theme",
    fThemeV: "Protyabartan, the homecoming",
    fActs: "Named that morning",
    fActsV: "KRL Bengal. Mahila Wing. Krishak Samaj Durga Puja 2026.",
    inviteTitle: "The invitation, as printed",
    inviteLede:
      "Issued in English and Bangla from Bharatiya Krishak Samaj West Bengal and KarmYog. The card is an artefact of the morning. Body copy of this essay names only those who were in the hall.",
    capInviteEn: "English invitation. 9:30 AM. Rabindra Okakura Bhawan.",
    capInviteBn: "Bengali invitation. Same morning, same hall.",
    progTitle: "The printed programme",
    progLede: "The order as issued. Photographs below carry the live room.",
    p1t: "09:30",
    p1: "Sacred opening. KarmYog Seva Mantra and Vande Mataram.",
    p2t: "09:35",
    p2: "Welcome and stage call. Smt. Reena J. Sarkar.",
    p3t: "09:40",
    p3: "Video testimonial. Shri Partha S. Chatterjee, Global Ambassador, BKS West Bengal. Video keynote from Dr. Krishan Bir Chaudhary.",
    p4t: "09:50",
    p4: "Foundational vision and KRL Bengal launch. MahAcharya Shri Sourabh J. Sarkar.",
    p5t: "10:05",
    p5: "Felicitation of Smt. Rinku Majumder Ghosh, Adhyaksha, Mahila Wing.",
    p6t: "10:10",
    p6: "Ministerial address. Shri Dudh Kumar Mondal, Hon'ble Minister of Agriculture, West Bengal.",
    p7t: "10:25",
    p7: "Keynote. Smt. Rinku Majumder Ghosh.",
    p8t: "10:35",
    p8: "Guest of Honour. Shri Debashish Dhar, MLA, Sonarpur Uttar.",
    p9t: "10:45",
    p9: "Krishak Samaj Durga Puja 2026 announcement. Smt. Reena J. Sarkar.",
    p10t: "10:50",
    p10: "Media questions. MahAcharya Shri Sourabh J. Sarkar and Smt. Rinku Majumder Ghosh.",
    p11t: "11:10",
    p11: "Vote of thanks and National Anthem. Smt. Reena J. Sarkar.",
    roomTitle: "The room",
    roomLede:
      "Bamboo, diya, tulsi, a yellow cloth on the lectern. The hall at Okakura before the first greeting.",
    capStage:
      "Stage set. Welcome banner, puja, and the four invited faces as printed.",
    openTitle: "The greeting",
    capOpen:
      "MahAcharya Shri Sourabh J. Sarkar at the lectern. Gunamata Reena J. Sarkar, Smt. Rinku Majumder Ghosh and Shri Dudh Kumar Mondal on the bamboo seats.",
    parthaTitle: "The video testimonial",
    parthaLede:
      "The hall played the film of Shri Partha S. Chatterjee, Global Ambassador and Senior Advisor for AI, Technology and Energy Transition, Bharatiya Krishak Samaj West Bengal.",
    parthaName: "Shri Partha S. Chatterjee",
    parthaRole: "Global Ambassador, BKS West Bengal",
    capPartha:
      "The card that sat with the film. Four minutes forty-seven seconds.",
    minTitle: "The Minister",
    minLede:
      "Shri Dudh Kumar Mondal, Hon'ble Minister of Agriculture, West Bengal, was on the stage at the opening. Krishi Ratna League Bengal was named in that room.",
    capMinListen:
      "MahAcharya Shri Sourabh J. Sarkar at the lectern. Smt. Rinku Majumder Ghosh and Shri Dudh Kumar Mondal listening.",
    capMinPair:
      "Smt. Rinku Majumder Ghosh with Shri Dudh Kumar Mondal, Hon'ble Minister of Agriculture, on stage.",
    capMin:
      "Shri Dudh Kumar Mondal, Hon'ble Minister of Agriculture, West Bengal.",
    capMinFeature:
      "Shri Dudh Kumar Mondal, Hon'ble Minister of Agriculture, with Smt. Rinku Majumder Ghosh and Gunamata Reena J. Sarkar.",
    rinkuTitle: "Adhyaksha",
    rinkuLede:
      "Smt. Rinku Majumder Ghosh was felicitated as Adhyaksha of the Mahila Wing, Bharatiya Krishak Samaj West Bengal. The badge sat on the pink sari for the rest of the morning.",
    capRinku: "Smt. Rinku Majumder Ghosh.",
    capTrio:
      "Gunamata Reena J. Sarkar, Smt. Rinku Majumder Ghosh and Shri Debashish Dhar, MLA.",
    capBell:
      "The bell. Standing for the felicitation. MahAcharya Shri Sourabh J. Sarkar, Gunamata Reena J. Sarkar, Smt. Rinku Majumder Ghosh and Shri Debashish Dhar, MLA.",
    capRinkuPodium:
      "Smt. Rinku Majumder Ghosh at the lectern. The keynote, 10:25.",
    dharTitle: "Guest of Honour",
    dharLede:
      "Shri Debashish Dhar, MLA, Sonarpur Uttar, addressed the hall from the yellow-draped lectern.",
    capDhar: "Shri Debashish Dhar at the lectern.",
    capGarland: "A garland on the Guest of Honour. The hall photographing.",
    voicesTitle: "What the stage carried",
    voicesNote:
      "The argument of the morning, in each voice. Exact words from the recordings will replace these lines.",
    v1n: "Shri Dudh Kumar Mondal",
    v1r: "Hon'ble Minister of Agriculture, West Bengal",
    v1: "The farmer is not a backdrop to policy. Krishi Ratna League puts the field at the centre of Bengal's next public contest.",
    v2n: "Smt. Rinku Majumder Ghosh",
    v2r: "Adhyaksha, Mahila Wing, Bharatiya Krishak Samaj",
    v2: "Half of Bengal's farm is a woman. The Mahila Wing is not a side room of the Samaj.",
    v3n: "Shri Debashish Dhar",
    v3r: "MLA, Sonarpur Uttar",
    v3: "Protyabartan is not nostalgia. It is the village asking its children to stand with the soil again.",
    v4n: "MahAcharya Shri Sourabh J. Sarkar",
    v4r: "State President, BKS West Bengal. KarmYog Ashram",
    v4: "A league with a working farm at the end of it, not a trophy on a shelf.",
    hallTitle: "The hall",
    capHall: "Press, farmers, the team. Rabindra Okakura Bhawan.",
    capLaunch:
      "Launch of Krishi Ratna League Bengal on the screen. MahAcharya Shri Sourabh J. Sarkar at the lectern. Gunamata Reena J. Sarkar, Smt. Rinku Majumder Ghosh and Shri Debashish Dhar, MLA, seated.",
    pressTitle: "The press huddle",
    pressLede:
      "After the programme the mics closed in. MahAcharya Shri Sourabh J. Sarkar, Smt. Rinku Majumder Ghosh, Shri Debashish Dhar, MLA, and Gunamata Reena J. Sarkar took the questions together. Bonglive, 24 Ghanta and the rest of the room stayed until the last answer.",
    capPanel:
      "The press panel. Seated, left to right: Shri Rajib Roy, Gunamata Reena J. Sarkar, MahAcharya Shri Sourabh J. Sarkar, Smt. Rinku Majumder Ghosh and Shri Debashish Dhar, MLA. Mics on the yellow cloth.",
    capHuddle: "Cameras in. MahAcharya Shri Sourabh J. Sarkar facing the room.",
    capPressDhar: "Shri Debashish Dhar to the mics.",
    capClose: "Outside Rabindra Okakura Bhawan after the morning.",
    navGuests: "Guests",
    guestsTitle: "The guests",
    guestsLede:
      "Who sat on the panel, in the order they sat. Titles as held on the day.",
    gn1: "Shri Rajib Roy",
    gr1: "",
    gn2: "Gunamata Reena J. Sarkar",
    gr2: "Chief of Technology, Bharatiya Krishak Samaj. Co-Founder and CTO, KarmYog for the 21st Century",
    gn3: "MahAcharya Shri Sourabh J. Sarkar",
    gr3: "State President, Bharatiya Krishak Samaj West Bengal. KarmYog Ashram",
    gn4: "Smt. Rinku Majumder Ghosh",
    gr4: "Adhyaksha, Mahila Wing, Bharatiya Krishak Samaj West Bengal",
    gn5: "Shri Debashish Dhar",
    gr5: "MLA, Sonarpur Uttar",
    capArrival:
      "Arrival at Rabindra Okakura Bhawan. The conch and the bell before the hall opened.",
    capTrioOutside:
      "Gunamata Reena J. Sarkar with guests outside Rabindra Okakura Bhawan.",
    capGuestsArrival:
      "Guests gathering outside Rabindra Okakura Bhawan before the hall opened.",
    capHospitality:
      "Hospitality in the green room. Clay cups carried round before the programme.",
    capHallFront:
      "The front rows, listening. Press, farmers and the Samaj together.",
    galleryTitle: "From the hall",
    galleryLede:
      "Stills and clips from the Media Connect. The Krishi Ratna League intro played behind the welcome.",
    g1: "From the stage into the hall.",
    g2: "Shri Dudh Kumar Mondal, Hon'ble Minister of Agriculture, West Bengal.",
    g3: "Green room. A clay cup for Shri Dudh Kumar Mondal.",
    g4: "Shri Debashish Dhar at the lectern.",
    g5: "The press, full stage.",
    g6: "Gunamata Reena J. Sarkar.",
    g7: "Krishi Ratna League Bengal on the screen.",
    gv1: "Clip from the hall.",
    gv2: "Clip from the hall.",
    gv3: "Clip from the hall.",
    gv4: "Clip from the hall.",
    gv5: "Clip from the hall.",
    gv6: "Clip from the hall.",
    gv7: "Clip from the hall.",
    mediaTitle: "In the media",
    mediaLede:
      "A running record of the coverage. Clippings, broadcast and video from the morning of 14 September 2026 are added here as they appear.",
    mediaVidName: "Media Connect, on camera",
    mediaVidRole: "YouTube · 14 September 2026",
    mediaVidCap:
      "Footage from the Media Connect session at Rabindra Okakura Bhawan.",
    mediaVidLink: "Watch on YouTube",
    mediaVid2Name: "Media Connect — Interview with Shri Dudh Kumar Mondal",
    mediaVid2Role: "YouTube · 14 September 2026",
    mediaVid2Cap:
      "Shri Dudh Kumar Mondal, Hon'ble Minister of Agriculture, West Bengal, on camera at Rabindra Okakura Bhawan.",
    mediaVid2Link: "Watch on YouTube",
    clipTitle: "In print",
    clipOutlet: "Hello Evening Kolkata · Page 07 · 14 September 2026",
    clipHead: "Focus on better facilities for Farmers in WB",
    clipBody:
      "Reported by Asish Basak on the Hello Kolkata Focus page. The Media Connect session, the Krishi Ratna League announcement, and Smt. Rinku Majumder Ghosh on the holistic development of farmers after her induction as Chief of the Ladies Wing, BKS West Bengal.",
    clipDl: "Download the page (PDF)",
    capClip: "Hello Evening Kolkata, page 07, Monday, 14 September 2026.",
    releaseTitle: "The press release",
    releaseHead:
      "Bharatiya Krishak Samaj West Bengal with KarmYog for the 21st Century",
    releaseBody:
      "Issued for immediate release. Ref BKS-WB/PR/2026/09-14. Krishi Ratna League launched with AI-driven farmer outreach, Smt. Rinku Majumder Ghosh felicitated as State Adhyaksha, and the Durga Puja 2026 theme Protyabartan unveiled. English and Bangla, two pages.",
    releaseDl: "Download the press release (PDF)",
    footOrgs:
      "Bharatiya Krishak Samaj West Bengal, with KarmYog for the 21st Century.",
    footPhotos: "Photographs: Bumba and Shubhashis.",
    footRsvp:
      "Smt. Reena J. Sarkar +91 98300 24611. Shri Ram Badrinathan +91 91677 19898.",
    footPlace:
      "State office: F-127, Downtown Mall, Uniworld City, New Town, Kolkata 700156.",
  },
  bn: {
    navDay: "সেই দিন",
    navGallery: "গ্যালারি",
    navPress: "প্রেস",
    navMedia: "সংবাদমাধ্যম",
    brand: "মিডিয়া সংযোগ",
    heroKicker: "১৪ সেপ্টেম্বর ২০২৬",
    heroTitle: "প্রত্যাবর্তন",
    heroSub:
      "রবীন্দ্র ওকাকুরা ভবনে একটি মিডিয়া সংযোগ অনুষ্ঠান. কৃষি রত্ন লীগ বাংলা শুরু.",
    fDate: "তারিখ",
    fDateV: "সোমবার, ১৪ সেপ্টেম্বর ২০২৬",
    fPlace: "স্থান",
    fPlaceV: "রবীন্দ্র ওকাকুরা ভবন, ডিডি ব্লক, সল্টলেক, কলকাতা",
    fTheme: "থিম",
    fThemeV: "প্রত্যাবর্তন, ফিরে আসা",
    fActs: "সেই সকালে যা ঘোষিত",
    fActsV: "কৃষি রত্ন লীগ বাংলা. মহিলা শাখা. কৃষক সমাজের দুর্গা পূজা ২০২৬.",
    inviteTitle: "নিমন্ত্রণপত্র, যেমন ছাপা হয়েছিল",
    inviteLede:
      "ইংরেজি ও বাংলায়. ভারতীয় কৃষক সমাজ পশ্চিমবঙ্গ এবং কর্মযোগ. ছাপা কার্ডটি সেই সকালের একটি দলিল. এই রচনায় নাম শুধু তাঁদেরই, যাঁরা হলে ছিলেন.",
    capInviteEn: "ইংরেজি নিমন্ত্রণপত্র. সকাল ৯:৩০. রবীন্দ্র ওকাকুরা ভবন.",
    capInviteBn: "বাংলা নিমন্ত্রণপত্র. একই সকাল, একই হল.",
    progTitle: "ছাপা কার্যক্রম",
    progLede: "যে ক্রমে লেখা হয়েছিল. নিচের ছবিগুলি সেই ঘরকে ধরেছে.",
    p1t: "০৯:৩০",
    p1: "পবিত্র সূচনা. কর্মযোগ সেবা মন্ত্র ও বন্দে মাতরম.",
    p2t: "০৯:৩৫",
    p2: "স্বাগত ও মঞ্চ আহ্বান. শ্রীমতি রীনা জে. সরকার.",
    p3t: "০৯:৪০",
    p3: "ভিডিও সাক্ষ্য. শ্রী পার্থ এস. চ্যাটার্জি, গ্লোবাল অ্যাম্বাসেডর, বি কে এস পশ্চিমবঙ্গ. ড. কৃষণ বীর চৌধুরীর ভিডিও মূল বক্তব্য.",
    p4t: "০৯:৫০",
    p4: "মূল দর্শন ও কৃষি রত্ন লীগ বাংলা উদ্বোধন. মহাচার্য শ্রী সৌরভ জে. সরকার.",
    p5t: "১০:০৫",
    p5: "শ্রীমতি রিঙ্কু মজুমদার ঘোষের সম্মাননা. অধ্যক্ষা, মহিলা শাখা.",
    p6t: "১০:১০",
    p6: "মন্ত্রীর ভাষণ. শ্রী দুধ কুমার মণ্ডল, মাননীয় কৃষিমন্ত্রী, পশ্চিমবঙ্গ.",
    p7t: "১০:২৫",
    p7: "মূল ভাষণ. শ্রীমতি রিঙ্কু মজুমদার ঘোষ.",
    p8t: "১০:৩৫",
    p8: "প্রধান অতিথি. শ্রী দেবাশীষ ধর, বিধায়ক, সোনারপুর উত্তর.",
    p9t: "১০:৪৫",
    p9: "কৃষক সমাজের দুর্গা পূজা ২০২৬ ঘোষণা. শ্রীমতি রীনা জে. সরকার.",
    p10t: "১০:৫০",
    p10: "মিডিয়া প্রশ্ন. মহাচার্য শ্রী সৌরভ জে. সরকার ও শ্রীমতি রিঙ্কু মজুমদার ঘোষ.",
    p11t: "১১:১০",
    p11: "ধন্যবাদ ও জাতীয় সঙ্গীত. শ্রীমতি রীনা জে. সরকার.",
    roomTitle: "ঘর",
    roomLede:
      "বাঁশ, প্রদীপ, তুলসি, হলুদ কাপড়ে ঢাকা বেদি. প্রথম নমস্কারের আগে ওকাকুরার হল.",
    capStage: "মঞ্চ. স্বাগত ব্যানার, পূজা, এবং ছাপা নিমন্ত্রণের চার মুখ.",
    openTitle: "নমস্কার",
    capOpen:
      "মহাচার্য শ্রী সৌরভ জে. সরকার বেদিতে. গুণমাতা রীনা জে. সরকার, শ্রীমতি রিঙ্কু মজুমদার ঘোষ ও শ্রী দুধ কুমার মণ্ডল বাঁশের আসনে.",
    parthaTitle: "ভিডিও সাক্ষ্য",
    parthaLede:
      "হলে দেখানো হয় শ্রী পার্থ এস. চ্যাটার্জির সাক্ষ্যচিত্র. তিনি ভারতীয় কৃষক সমাজ পশ্চিমবঙ্গের গ্লোবাল অ্যাম্বাসেডর এবং এআই, প্রযুক্তি ও শক্তি রূপান্তরের সিনিয়র অ্যাডভাইজার.",
    parthaName: "শ্রী পার্থ এস. চ্যাটার্জি",
    parthaRole: "গ্লোবাল অ্যাম্বাসেডর, বি কে এস পশ্চিমবঙ্গ",
    capPartha: "ছবির সঙ্গে যে কার্ডটি ছিল. চার মিনিট সাতচল্লিশ সেকেন্ড.",
    minTitle: "মন্ত্রী",
    minLede:
      "শ্রী দুধ কুমার মণ্ডল, মাননীয় কৃষিমন্ত্রী, পশ্চিমবঙ্গ, মিডিয়া সংযোগের সূচনায় মঞ্চে ছিলেন. কৃষি রত্ন লীগ বাংলা সেই ঘরেই নাম পেল.",
    capMinListen:
      "বেদিতে মহাচার্য শ্রী সৌরভ জে. সরকার. শ্রীমতি রিঙ্কু মজুমদার ঘোষ ও শ্রী দুধ কুমার মণ্ডল শুনছেন.",
    capMinPair:
      "মঞ্চে শ্রীমতি রিঙ্কু মজুমদার ঘোষ এবং শ্রী দুধ কুমার মণ্ডল, মাননীয় কৃষিমন্ত্রী.",
    capMin: "শ্রী দুধ কুমার মণ্ডল, মাননীয় কৃষিমন্ত্রী, পশ্চিমবঙ্গ.",
    capMinFeature:
      "শ্রী দুধ কুমার মণ্ডল, মাননীয় কৃষিমন্ত্রী, শ্রীমতি রিঙ্কু মজুমদার ঘোষ ও গুণমাতা রীনা জে. সরকারের সঙ্গে.",
    rinkuTitle: "অধ্যক্ষা",
    rinkuLede:
      "শ্রীমতি রিঙ্কু মজুমদার ঘোষকে ভারতীয় কৃষক সমাজ পশ্চিমবঙ্গের মহিলা শাখার অধ্যক্ষা হিসেবে সম্মাননা জানানো হয়. গোলাপি শাড়িতে ব্যাজটি সকালভর ছিল.",
    capRinku: "শ্রীমতি রিঙ্কু মজুমদার ঘোষ.",
    capTrio:
      "গুণমাতা রীনা জে. সরকার, শ্রীমতি রিঙ্কু মজুমদার ঘোষ ও শ্রী দেবাশীষ ধর, বিধায়ক.",
    capBell:
      "ঘণ্টা. সম্মাননায় দাঁড়ানো. মহাচার্য শ্রী সৌরভ জে. সরকার, গুণমাতা রীনা জে. সরকার, শ্রীমতি রিঙ্কু মজুমদার ঘোষ ও শ্রী দেবাশীষ ধর, বিধায়ক.",
    capRinkuPodium: "বেদিতে শ্রীমতি রিঙ্কু মজুমদার ঘোষ. মূল ভাষণ, ১০:২৫.",
    dharTitle: "প্রধান অতিথি",
    dharLede:
      "শ্রী দেবাশীষ ধর, বিধায়ক, সোনারপুর উত্তর, হলুদ কাপড়ে ঢাকা বেদি থেকে হলকে সম্বোধন করেন.",
    capDhar: "বেদিতে শ্রী দেবাশীষ ধর.",
    capGarland: "প্রধান অতিথিকে মালা. হল ছবি তুলছে.",
    voicesTitle: "মঞ্চ যা বলেছিল",
    voicesNote:
      "সেই সকালের যুক্তি, প্রতিটি কণ্ঠে. রেকর্ডিং থেকে ঠিক কথাগুলি পরে বসবে.",
    v1n: "শ্রী দুধ কুমার মণ্ডল",
    v1r: "মাননীয় কৃষিমন্ত্রী, পশ্চিমবঙ্গ",
    v1: "কৃষক নীতির পেছনের দৃশ্য নন. কৃষি রত্ন লীগ বাংলার পরের জনপ্রতিযোগিতার কেন্দ্রে ক্ষেতকে রাখে.",
    v2n: "শ্রীমতি রিঙ্কু মজুমদার ঘোষ",
    v2r: "অধ্যক্ষা, মহিলা শাখা, ভারতীয় কৃষক সমাজ",
    v2: "বাংলার ক্ষেতের অর্ধেক একজন নারী. মহিলা শাখা সমাজের পাশের ঘর নয়.",
    v3n: "শ্রী দেবাশীষ ধর",
    v3r: "বিধায়ক, সোনারপুর উত্তর",
    v3: "প্রত্যাবর্তন নস্টালজিয়া নয়. গ্রাম তার সন্তানদের মাটির পাশে দাঁড়াতে বলছে.",
    v4n: "মহাচার্য শ্রী সৌরভ জে. সরকার",
    v4r: "রাজ্য সভাপতি, বি কে এস পশ্চিমবঙ্গ. কর্মযোগ আশ্রম",
    v4: "শেষে একটি কাজ করা খামার নিয়ে লীগ, তাকে তাকের ট্রফি নয়.",
    hallTitle: "হল",
    capHall: "প্রেস, কৃষক, দল. রবীন্দ্র ওকাকুরা ভবন.",
    capLaunch:
      "পর্দায় কৃষি রত্ন লীগ বাংলার উদ্বোধন. বেদিতে মহাচার্য শ্রী সৌরভ জে. সরকার. আসনে গুণমাতা রীনা জে. সরকার, শ্রীমতি রিঙ্কু মজুমদার ঘোষ ও শ্রী দেবাশীষ ধর, বিধায়ক.",
    pressTitle: "প্রেস আড্ডা",
    pressLede:
      "অনুষ্ঠানের পর মাইক্রোফোন এগিয়ে এল. মহাচার্য শ্রী সৌরভ জে. সরকার, শ্রীমতি রিঙ্কু মজুমদার ঘোষ, শ্রী দেবাশীষ ধর, বিধায়ক, এবং গুণমাতা রীনা জে. সরকার একসঙ্গে প্রশ্ন নিলেন. বংলাইভ, ২৪ ঘণ্টা এবং ঘরের বাকিরা শেষ উত্তর পর্যন্ত ছিলেন.",
    capPanel:
      "প্রেস প্যানেল. বাঁ দিক থেকে ডান দিকে আসনে: শ্রী রাজীব রায়, গুণমাতা রীনা জে. সরকার, মহাচার্য শ্রী সৌরভ জে. সরকার, শ্রীমতি রিঙ্কু মজুমদার ঘোষ ও শ্রী দেবাশীষ ধর, বিধায়ক. হলুদ কাপড়ে মাইক.",
    capHuddle: "ক্যামেরা এগিয়ে. মহাচার্য শ্রী সৌরভ জে. সরকার ঘরের দিকে.",
    capPressDhar: "মাইকের সামনে শ্রী দেবাশীষ ধর.",
    capClose: "রবীন্দ্র ওকাকুরা ভবনের বাইরে, সকালের পর.",
    navGuests: "অতিথি",
    guestsTitle: "অতিথিবৃন্দ",
    guestsLede:
      "প্যানেলে যাঁরা বসেছিলেন, যে ক্রমে বসেছিলেন. পদবি সেই দিনের অনুযায়ী.",
    gn1: "শ্রী রাজীব রায়",
    gr1: "",
    gn2: "গুণমাতা রীনা জে. সরকার",
    gr2: "চিফ অফ টেকনোলজি, ভারতীয় কৃষক সমাজ. সহ-প্রতিষ্ঠাতা ও সিটিও, কর্মযোগ ফর দ্য টোয়েন্টিফার্স্ট সেঞ্চুরি",
    gn3: "মহাচার্য শ্রী সৌরভ জে. সরকার",
    gr3: "রাজ্য সভাপতি, ভারতীয় কৃষক সমাজ পশ্চিমবঙ্গ. কর্মযোগ আশ্রম",
    gn4: "শ্রীমতি রিঙ্কু মজুমদার ঘোষ",
    gr4: "অধ্যক্ষা, মহিলা শাখা, ভারতীয় কৃষক সমাজ পশ্চিমবঙ্গ",
    gn5: "শ্রী দেবাশীষ ধর",
    gr5: "বিধায়ক, সোনারপুর উত্তর",
    capArrival: "রবীন্দ্র ওকাকুরা ভবনে আগমন. হল খোলার আগে শঙ্খ ও ঘণ্টা.",
    capTrioOutside:
      "রবীন্দ্র ওকাকুরা ভবনের বাইরে গুণমাতা রীনা জে. সরকার অতিথিদের সঙ্গে.",
    capGuestsArrival: "হল খোলার আগে রবীন্দ্র ওকাকুরা ভবনের বাইরে অতিথিরা.",
    capHospitality: "গ্রিন রুমে আপ্যায়ন. অনুষ্ঠানের আগে মাটির কাপে চা.",
    capHallFront:
      "সামনের সারি, মন দিয়ে শুনছে. সংবাদমাধ্যম, কৃষক ও সমাজ একসঙ্গে.",
    galleryTitle: "হল থেকে",
    galleryLede:
      "মিডিয়া সংযোগের ছবি ও ক্লিপ. স্বাগত ব্যানারের পেছনে কৃষি রত্ন লীগের ইন্ট্রো চলে.",
    g1: "মঞ্চ থেকে হলের দিকে.",
    g2: "শ্রী দুধ কুমার মণ্ডল, মাননীয় কৃষিমন্ত্রী, পশ্চিমবঙ্গ.",
    g3: "গ্রিন রুম. শ্রী দুধ কুমার মণ্ডলের জন্য মাটির কাপ.",
    g4: "বেদিতে শ্রী দেবাশীষ ধর.",
    g5: "প্রেস, পুরো মঞ্চ.",
    g6: "গুণমাতা রীনা জে. সরকার.",
    g7: "পর্দায় কৃষি রত্ন লীগ বাংলা.",
    gv1: "হলের ক্লিপ.",
    gv2: "হলের ক্লিপ.",
    gv3: "হলের ক্লিপ.",
    gv4: "হলের ক্লিপ.",
    gv5: "হলের ক্লিপ.",
    gv6: "হলের ক্লিপ.",
    gv7: "হলের ক্লিপ.",
    mediaTitle: "সংবাদমাধ্যমে",
    mediaLede:
      "সংবাদ-প্রচারের চলমান নথি. ১৪ই সেপ্টেম্বর ২০২৬ সকালের কাগজের কাটিং, সম্প্রচার ও ভিডিও যত প্রকাশিত হবে, এখানেই যুক্ত হবে.",
    mediaVidName: "ক্যামেরায় মিডিয়া সংযোগ",
    mediaVidRole: "ইউটিউব · ১৪ সেপ্টেম্বর ২০২৬",
    mediaVidCap: "রবীন্দ্র ওকাকুরা ভবনে মিডিয়া সংযোগ অনুষ্ঠানের ফুটেজ.",
    mediaVidLink: "ইউটিউবে দেখুন",
    mediaVid2Name: "মিডিয়া সংযোগ — শ্রী দুধ কুমার মণ্ডলের সাক্ষাৎকার",
    mediaVid2Role: "ইউটিউব · ১৪ সেপ্টেম্বর ২০২৬",
    mediaVid2Cap:
      "শ্রী দুধ কুমার মণ্ডল, মাননীয় কৃষিমন্ত্রী, পশ্চিমবঙ্গ, রবীন্দ্র ওকাকুরা ভবনে ক্যামেরার সামনে.",
    mediaVid2Link: "ইউটিউবে দেখুন",
    clipTitle: "ছাপার অক্ষরে",
    clipOutlet: "হ্যালো ইভনিং কলকাতা · পৃষ্ঠা ০৭ · ১৪ সেপ্টেম্বর ২০২৬",
    clipHead: "Focus on better facilities for Farmers in WB",
    clipBody:
      "‘হ্যালো কলকাতা ফোকাস’ পাতায় আশিস বসাকের প্রতিবেদন. মিডিয়া সংযোগ অনুষ্ঠান, কৃষি রত্ন লিগের ঘোষণা, এবং ভারতীয় কৃষক সমাজ পশ্চিমবঙ্গের মহিলা শাখার প্রধান হিসেবে অভিষেকের পর কৃষকের সার্বিক উন্নয়ন নিয়ে শ্রীমতি রিঙ্কু মজুমদার ঘোষের বক্তব্য.",
    clipDl: "পৃষ্ঠাটি ডাউনলোড করুন (পিডিএফ)",
    capClip: "হ্যালো ইভনিং কলকাতা, পৃষ্ঠা ০৭, সোমবার, ১৪ সেপ্টেম্বর ২০২৬.",
    releaseTitle: "প্রেস বিজ্ঞপ্তি",
    releaseHead:
      "ভারতীয় কৃষক সমাজ পশ্চিমবঙ্গ, কর্মযোগ ফর দ্য ২১স্ট সেঞ্চুরির সঙ্গে",
    releaseBody:
      "অবিলম্বে প্রকাশের জন্য. স্মারক নং BKS-WB/PR/2026/09-14. এআই-ভিত্তিক কৃষক কল্যাণ উদ্যোগ সহ ‘কৃষি রত্ন লিগ’-এর সূচনা, রাজ্য অধ্যক্ষা হিসেবে শ্রীমতি রিঙ্কু মজুমদার ঘোষকে সংবর্ধনা, এবং দুর্গাপূজা ২০২৬-এর থিম ‘প্রত্যাবর্তন’ উন্মোচন. ইংরেজি ও বাংলা, দুই পৃষ্ঠা.",
    releaseDl: "প্রেস বিজ্ঞপ্তি ডাউনলোড করুন (পিডিএফ)",
    footOrgs:
      "ভারতীয় কৃষক সমাজ পশ্চিমবঙ্গ, কর্মযোগ ফর দ্য ২১স্ট সেঞ্চুরির সঙ্গে.",
    footPhotos: "ছবি: বুম্বা এবং শুভাশিস.",
    footRsvp:
      "শ্রীমতি রীনা জে. সরকার +৯১ ৯৮৩০০ ২৪৬১১. শ্রী রাম বদ্রীনাথন +৯১ ৯১৬৭৭ ১৯৮৯৮.",
    footPlace:
      "রাজ্য কার্যালয়: এফ-১২৭, ডাউনটাউন মল, ইউনিওয়ার্ল্ড সিটি, নিউ টাউন, কলকাতা ৭০০১৫৬.",
  },
};
