// Approved copy from the editorial brief. Source-dependent additions are tracked
// outside the deployed site in ../EDITORIAL-REVIEW.md.
const EDITORIAL_COPY = {
  en: {
    pressCollectionTitle: "Across the newspapers",
    pressCollectionHint: "Select a clipping to read, zoom and browse all five. Original editions are preserved as published.",
    pressRead: "Read & zoom ↗",
    pressHelloCaption: "Hello Evening Kolkata · 14 September 2026 · English. Original press clipping supplied by the organisers.",
    pressPrathamName: "Dainik Pratham",
    pressPrathamDate: "15 September 2026 · Bengali",
    pressPrathamCaption: "Dainik Pratham · 15 September 2026 · Bengali. Original press clipping supplied by the organisers.",
    pressWorldName: "World Watch",
    pressWorldDate: "16 September 2026 · English",
    pressWorldCaption: "World Watch · 16 September 2026 · English. Original press clipping supplied by the organisers.",
    pressAroName: "Aro Khabar",
    pressAroDate: "16 September 2026 · Bengali",
    pressAroCaption: "Aro Khabar · 16 September 2026 · Bengali. Original press clipping supplied by the organisers.",
    pressJhalakName: "Shaam Ki Jhalak",
    pressJhalakDate: "15 September 2026 · Hindi",
    pressJhalakCaption: "Shaam Ki Jhalak · 15 September 2026 · Hindi. Original press clipping supplied by the organisers.",
    committeeKicker: "ANNOUNCEMENT / BHARATIYA KRISHAK SAMAJ",
    committeeTitle: "The Central Committee",
    committeeIntro: "The formation of the Central Committee for Bharatiya Krishak Samaj was announced, with the following members inducted:",
    committee1: "Shri Ram Badrinathan",
    committee2: "Smt. Reena J. Sarkar",
    committee3: "Shri Akhilesh Kumar Singh",
    committee4: "Shri Rajiv Roy",
    committee5: "Shri Amit Bansal",
    committee6: "Dr. Swapan Chakravarty",
    committee7: "Shri Kalyan Mukherjee (Retd. IPS)",
    committee8: "Shri Apurba Bera",
    committee9: "Shri Kalyan Bhattacharya",
    committee10: "Shri Subhashis Ghosh",
    ministerKicker: "10:10 / THE MINISTERIAL ADDRESS",
    ministerTitle: "Farmer welfare at the centre",
    ministerQuote1: "“Farmers are the critical foundation of Bengal’s economic strength.”",
    ministerQuote2: "“The Krishi Ratna League provides vital encouragement to our cultivators, supporting farmer welfare and sustainable agricultural development across the state.”",
    ministerSource: "Excerpts published in the official release · 14 September 2026 ↗",
    ministerCaption: "Shri Dudh Kumar Mondal, Hon'ble Minister of Agriculture, West Bengal, at the Media Connect session.",
    guestsLede: "The speakers, hosts and participants who came together for Bengal’s farmers.",
    attendanceTitle: "The people behind the gathering",
    attendanceFarmers: "A dedicated pool of Farmers and Agri-Karigars attended the session, bringing the farming community into the conversation.",
    attendanceCii: "Shri Subhajyoti Chakraborty of CII was present among the attendees.",
    attendanceKris: "Kris’s team was also present and extended its support to the session.",
    attendanceCaption: "Participants gathered in the hall at Rabindra Okakura Bhawan.",
    heroRegion: "Bengal",
    heroFootage: "FROM THE MEDIA CONNECT",
    heroExplore: "Discover the League",
    eventName: "Media Connect Session & Agri-Innovation Convening",
    chapter2: "02 / THE LAUNCH",
    launchKicker: "KRISHI RATNA LEAGUE — BENGAL",
    launchAnnounced: "Announced from the stage at 09:50 by MahAcharya Shri. sourabh J. sarkar, and placed before Bengal by Smt. Rinku Majumder Ghosh in her acceptance address.",
    launchBody: "Across West Bengal, the League will mobilise and train 5,000 farmers in global cutting-edge Smart Farming and Integrated Farming Systems (IFS). The training is structured. What follows it is a competition — objective, transparent — and the finest performers are conferred prestigious awards.",
    launchIntent: "The intent is plain: that a farmer's skill should be measured in the open, and recognised in the open.",
    farmerCount: "5,000",
    farmerCountLabel: "farmers across West Bengal",
    leagueTrain: "Structured training",
    leagueCompete: "Transparent competition",
    leagueRecognise: "Prestigious awards",
    launchAttribution: "— Smt. Rinku Majumder Ghosh, Adhyakshaa, Mahila Wing, BKS West Bengal",
    chapterAcceptance: "03 / THE ACCEPTANCE",
    acceptanceKicker: "THE BACKBONE OF BENGAL",
    acceptanceTitle: "Empowering women in smart farming",
    acceptanceIntro: "Smt. Rinku Majumder Ghosh accepted the office of Adhyakshaa, Mahila Wing, Bharatiya Krishak Samaj West Bengal, and delivered the acceptance address that named the League.",
    acceptanceName: "Smt. Rinku Majumder Ghosh",
    acceptanceRole: "Adhyakshaa (State President), Mahila Wing · Bharatiya Krishak Samaj, West Bengal",
    chapter3: "04 / THE PEOPLE",
    chapter4: "05 / IN THEIR OWN VOICE",
    chapterPuja: "06 / ROOTS TO POSSIBILITIES",
    pujaAnnounced: "Announced by Smt. Reena J. Sarkar at 10:45.",
    pujaKicker: "PROTYABARTAN · প্রত্যাবর্তন · THE HOMECOMING",
    pujaTitle: "Krishak Samaj Durga Puja 2026",
    pujaBody1: "At Sector V (Munshi Bheri, Salt Lake), Krishak Samaj Durga Puja 2026 will carry a comprehensive live model of the Krishi Ratna League — a working integrated farm, built on the pandal ground.",
    pujaBody2: "It will demonstrate how modern agrarian techniques unlock extraordinary productivity from compact landholdings: a sapling guided from seed to harvest to direct market linkage, generating farm surplus and lifting rural households into genuine prosperity.",
    pujaBody3: "Protyabartan is a three-year trilogy. Its core philosophy is Roots to Possibilities, and Possibilities to Prosperity.",
    pujaInvite: "Visitors are invited, with their families, to Sector V during Sharodotsav to see the integrated farm model first-hand.",
    pujaCaption: "The Protyabartan theme is unveiled: a three-year trilogy for Krishak Samaj Durga Puja.",
    chapter5: "07 / THE VISUAL ARCHIVE",
    chapter6: "08 / THE CONVERSATION CONTINUES",
    nextKicker: "THE NEXT STEP",
    nextTitle: "Continue the conversation.",
    doorPress: "Press",
    doorFarmers: "Farmers",
    doorVisit: "Visit",
    farmerDoor: "Krishi Ratna League training",
    farmerRead: "Explore the League ↗",
    visitDoor: "Sector V · Durga Puja 2026",
    visitRead: "Discover the integrated farm ↗",
    footerEdition: "KRISHI RATNA LEAGUE BENGAL / SEPTEMBER 2026",
    invitationEn: "English invitation",
    invitationBn: "বাংলা invitation",
    invitationHint: "Swipe to change language · Tap the card to enlarge",
    invitationPrevious: "Previous invitation",
    invitationNext: "Next invitation",
    invitationZoom: "Read full-size ↗",
    invitationPosition: "Invitation",
    zoomIn: "Zoom in +",
    zoomOut: "Fit image −",
    clipCaption1: "The opening address, with the original welcome artwork behind the bamboo stage.",
    clipCaption2: "The Mahila Wing felicitation on stage, beneath the announcement naming Smt. Rinku Majumder Ghosh.",
    clipCaption3: "An address from the yellow-draped lectern, as the women on the panel listen.",
    clipCaption4: "Smt. Rinku Majumder Ghosh honours Shri Debashish Dhar with flowers on stage.",
    clipCaption5: "Shri Debashish Dhar delivers his address from the lectern.",
    clipCaption6: "Reporters bring their microphones to the stage for the media questions.",
    clipCaption7: "Shri Debashish Dhar answers reporters in the press huddle.",
  },
  bn: {
    pressCollectionTitle: "সংবাদপত্রের পাতায়",
    pressCollectionHint: "বড় করে পড়তে একটি সংবাদপত্রের কাটিং বেছে নিন। একই সঙ্গে পাঁচটিই দেখতে পারবেন। মূল সংস্করণগুলি প্রকাশিত অবস্থায় সংরক্ষিত।",
    pressRead: "বড় করে পড়ুন ↗",
    pressHelloCaption: "হ্যালো ইভনিং কলকাতা · ১৪ সেপ্টেম্বর ২০২৬ · ইংরেজি। আয়োজকদের দেওয়া মূল সংবাদপত্রের কাটিং।",
    pressPrathamName: "দৈনিক প্রথম",
    pressPrathamDate: "১৫ সেপ্টেম্বর ২০২৬ · বাংলা",
    pressPrathamCaption: "দৈনিক প্রথম · ১৫ সেপ্টেম্বর ২০২৬ · বাংলা। আয়োজকদের দেওয়া মূল সংবাদপত্রের কাটিং।",
    pressWorldName: "ওয়ার্ল্ড ওয়াচ",
    pressWorldDate: "১৬ সেপ্টেম্বর ২০২৬ · ইংরেজি",
    pressWorldCaption: "ওয়ার্ল্ড ওয়াচ · ১৬ সেপ্টেম্বর ২০২৬ · ইংরেজি। আয়োজকদের দেওয়া মূল সংবাদপত্রের কাটিং।",
    pressAroName: "আরো খবর",
    pressAroDate: "১৬ সেপ্টেম্বর ২০২৬ · বাংলা",
    pressAroCaption: "আরো খবর · ১৬ সেপ্টেম্বর ২০২৬ · বাংলা। আয়োজকদের দেওয়া মূল সংবাদপত্রের কাটিং।",
    pressJhalakName: "শাম কি ঝলক",
    pressJhalakDate: "১৫ সেপ্টেম্বর ২০২৬ · হিন্দি",
    pressJhalakCaption: "শাম কি ঝলক · ১৫ সেপ্টেম্বর ২০২৬ · হিন্দি। আয়োজকদের দেওয়া মূল সংবাদপত্রের কাটিং।",
    committeeKicker: "ঘোষণা / ভারতীয় কৃষক সমাজ",
    committeeTitle: "কেন্দ্রীয় কমিটি",
    committeeIntro: "ভারতীয় কৃষক সমাজের কেন্দ্রীয় কমিটি গঠনের ঘোষণা করা হয়। কমিটিতে অন্তর্ভুক্ত সদস্যরা হলেন:",
    committee1: "শ্রী রাম বদ্রীনাথন",
    committee2: "শ্রীমতী রীনা জে. সরকার",
    committee3: "শ্রী অখিলেশ কুমার সিং",
    committee4: "শ্রী রাজীব রায়",
    committee5: "শ্রী অমিত বনসল",
    committee6: "ড. স্বপন চক্রবর্তী",
    committee7: "শ্রী কল্যাণ মুখার্জি (অবসরপ্রাপ্ত আইপিএস)",
    committee8: "শ্রী অপূর্ব বেরা",
    committee9: "শ্রী কল্যাণ ভট্টাচার্য",
    committee10: "শ্রী শুভাশিস ঘোষ",
    ministerKicker: "১০:১০ / কৃষিমন্ত্রীর ভাষণ",
    ministerTitle: "কেন্দ্রে কৃষকের কল্যাণ",
    ministerQuote1: "“কৃষকরাই বাংলার অর্থনৈতিক শক্তির মূল স্তম্ভ।”",
    ministerQuote2: "“কৃষি রত্ন লিগ আমাদের কৃষক ভাই-বোনদের অসামান্য উৎসাহ জোগাবে এবং রাজ্যজুড়ে টেকসই কৃষিউন্নয়ন ও কৃষক কল্যাণে এক সুদূরপ্রসারী ভূমিকা পালন করবে।”",
    ministerSource: "আনুষ্ঠানিক সংবাদ বিজ্ঞপ্তিতে প্রকাশিত উদ্ধৃতাংশ · ১৪ সেপ্টেম্বর ২০২৬ ↗",
    ministerCaption: "মিডিয়া সংযোগ অধিবেশনে পশ্চিমবঙ্গের মাননীয় কৃষিমন্ত্রী শ্রী দুধ কুমার মণ্ডল।",
    guestsLede: "বাংলার কৃষকদের জন্য একত্রিত বক্তা, আয়োজক ও অংশগ্রহণকারীরা।",
    attendanceTitle: "এই সমাবেশের মানুষজন",
    attendanceFarmers: "নিবেদিতপ্রাণ কৃষক ও কৃষি-কারিগরদের একটি দল অধিবেশনে অংশ নেন। তাঁদের উপস্থিতিতে আলোচনায় যুক্ত হয় কৃষক সমাজ।",
    attendanceCii: "অংশগ্রহণকারীদের মধ্যে উপস্থিত ছিলেন সিআইআই-এর শ্রী শুভজ্যোতি চক্রবর্তী।",
    attendanceKris: "ক্রিসের দলও উপস্থিত থেকে অধিবেশনে সহায়তা করেছে।",
    attendanceCaption: "রবীন্দ্র ওকাকুরা ভবনের হলে সমবেত অংশগ্রহণকারীরা।",
    heroRegion: "বাংলা",
    heroFootage: "মিডিয়া সংযোগের মুহূর্ত",
    heroExplore: "লীগ সম্পর্কে জানুন",
    eventName: "মিডিয়া সংযোগ অধিবেশন ও কৃষি উদ্ভাবন সম্মেলন",
    heroSub: "১৪ সেপ্টেম্বর ২০২৬, রবীন্দ্র ওকাকুরা ভবনে ভারতীয় কৃষক সমাজ পশ্চিমবঙ্গ বাংলার সামনে কৃষি রত্ন লীগকে তুলে ধরল: ৫,০০০ কৃষককে স্মার্ট ফার্মিং ও সমন্বিত চাষ পদ্ধতিতে প্রশিক্ষণ দেওয়া হবে, তারপর উন্মুক্ত প্রতিযোগিতায় তাঁদের দক্ষতা বিচার করা হবে।",
    chapter2: "০২ / সূচনা",
    launchKicker: "কৃষি রত্ন লীগ — বাংলা",
    launchAnnounced: "সকাল ০৯:৫০-এ মঞ্চ থেকে MahAcharya Shri. sourabh J. sarkar এই উদ্যোগ ঘোষণা করেন। শ্রীমতী রিঙ্কু মজুমদার ঘোষ তাঁর দায়িত্ব গ্রহণের ভাষণে বাংলার সামনে লীগকে তুলে ধরেন।",
    launchBody: "পশ্চিমবঙ্গ জুড়ে লীগ ৫,০০০ কৃষককে একত্র করবে এবং বিশ্বের অত্যাধুনিক স্মার্ট ফার্মিং ও সমন্বিত চাষ পদ্ধতিতে (IFS) প্রশিক্ষণ দেবে। এই প্রশিক্ষণ একটি সুনির্দিষ্ট কাঠামো অনুসরণ করবে। তার পরে হবে প্রতিযোগিতা — নিরপেক্ষ ও স্বচ্ছ — এবং সেরা কৃষকদের সম্মানজনক পুরস্কারে ভূষিত করা হবে।",
    launchIntent: "উদ্দেশ্য স্পষ্ট: কৃষকের দক্ষতার মূল্যায়ন হোক সকলের সামনে, স্বীকৃতিও মিলুক সকলের সামনে।",
    farmerCount: "৫,০০০",
    farmerCountLabel: "পশ্চিমবঙ্গ জুড়ে কৃষক",
    leagueTrain: "সুনির্দিষ্ট প্রশিক্ষণ",
    leagueCompete: "স্বচ্ছ প্রতিযোগিতা",
    leagueRecognise: "সম্মানজনক পুরস্কার",
    launchAttribution: "— শ্রীমতী রিঙ্কু মজুমদার ঘোষ, অধ্যক্ষা, মহিলা শাখা, ভারতীয় কৃষক সমাজ পশ্চিমবঙ্গ",
    chapterAcceptance: "০৩ / দায়িত্ব গ্রহণ",
    acceptanceKicker: "বাংলার মেরুদণ্ড",
    acceptanceTitle: "স্মার্ট চাষে নারীর ক্ষমতায়ন",
    acceptanceIntro: "শ্রীমতী রিঙ্কু মজুমদার ঘোষ ভারতীয় কৃষক সমাজ পশ্চিমবঙ্গের মহিলা শাখার অধ্যক্ষার দায়িত্ব গ্রহণ করেন। দায়িত্ব গ্রহণের ভাষণে তিনি কৃষি রত্ন লীগের কথা তুলে ধরেন।",
    acceptanceName: "শ্রীমতী রিঙ্কু মজুমদার ঘোষ",
    acceptanceRole: "অধ্যক্ষা (রাজ্য সভাপতি), মহিলা শাখা · ভারতীয় কৃষক সমাজ, পশ্চিমবঙ্গ",
    chapter3: "০৪ / মানুষজন",
    chapter4: "০৫ / তাঁদের নিজের কথায়",
    chapterPuja: "০৬ / শিকড় থেকে সম্ভাবনা",
    pujaAnnounced: "সকাল ১০:৪৫-এ ঘোষণা করেন শ্রীমতী রীনা জে. সরকার।",
    pujaKicker: "PROTYABARTAN · প্রত্যাবর্তন · ফিরে আসা",
    pujaTitle: "কৃষক সমাজ দুর্গাপূজা ২০২৬",
    pujaBody1: "সেক্টর ফাইভে (মুনশি ভেড়ি, সল্টলেক) কৃষক সমাজ দুর্গাপূজা ২০২৬-এ কৃষি রত্ন লীগের একটি পূর্ণাঙ্গ জীবন্ত মডেল তুলে ধরা হবে — মণ্ডপের প্রাঙ্গণেই গড়ে উঠবে একটি কার্যকর সমন্বিত খামার।",
    pujaBody2: "অল্প জমিতে আধুনিক কৃষিপদ্ধতি কীভাবে অসাধারণ উৎপাদন সম্ভব করে, এই মডেল তা দেখাবে: বীজ থেকে চারা, ফসল সংগ্রহ এবং সরাসরি বাজারের সঙ্গে সংযোগ — কৃষিতে উদ্বৃত্ত তৈরি করে গ্রামীণ পরিবারগুলিকে প্রকৃত সমৃদ্ধির পথে এগিয়ে দেওয়া।",
    pujaBody3: "প্রত্যাবর্তন তিন বছরের একটি ত্রয়ী। এর মূল দর্শন: শিকড় থেকে সম্ভাবনা, সম্ভাবনা থেকে সমৃদ্ধি।",
    pujaInvite: "শারদোৎসবে পরিবার নিয়ে সেক্টর ফাইভে এসে সমন্বিত খামারের মডেলটি নিজের চোখে দেখার আমন্ত্রণ রইল।",
    pujaCaption: "কৃষক সমাজ দুর্গাপূজার তিন বছরের ত্রয়ী ‘প্রত্যাবর্তন’-এর থিম উন্মোচন।",
    chapter5: "০৭ / ছবিতে সেই দিন",
    chapter6: "০৮ / কথোপকথন চলতে থাকে",
    nextKicker: "পরবর্তী পদক্ষেপ",
    nextTitle: "কথোপকথন চলুক।",
    doorPress: "সংবাদমাধ্যম",
    doorFarmers: "কৃষক",
    doorVisit: "আসুন",
    farmerDoor: "কৃষি রত্ন লীগের প্রশিক্ষণ",
    farmerRead: "লীগ সম্পর্কে জানুন ↗",
    visitDoor: "সেক্টর ফাইভ · দুর্গাপূজা ২০২৬",
    visitRead: "সমন্বিত খামার সম্পর্কে জানুন ↗",
    footerEdition: "কৃষি রত্ন লীগ বাংলা / সেপ্টেম্বর ২০২৬",
    invitationEn: "ইংরেজি নিমন্ত্রণপত্র",
    invitationBn: "বাংলা নিমন্ত্রণপত্র",
    invitationHint: "ভাষা বদলাতে সোয়াইপ করুন · বড় করে পড়তে কার্ডে চাপুন",
    invitationPrevious: "আগের নিমন্ত্রণপত্র",
    invitationNext: "পরের নিমন্ত্রণপত্র",
    invitationZoom: "বড় করে পড়ুন ↗",
    invitationPosition: "নিমন্ত্রণপত্র",
    zoomIn: "বড় করুন +",
    zoomOut: "পুরো ছবি −",
    clipCaption1: "বাঁশের মঞ্চের পিছনে মূল স্বাগত শিল্পকর্ম, সামনে সূচনার ভাষণ।",
    clipCaption2: "শ্রীমতী রিঙ্কু মজুমদার ঘোষের নামাঙ্কিত ঘোষণার সামনে মহিলা শাখার সংবর্ধনা।",
    clipCaption3: "হলুদ কাপড়ে ঢাকা বেদি থেকে ভাষণ, মঞ্চে মন দিয়ে শুনছেন মহিলারা।",
    clipCaption4: "মঞ্চে শ্রী দেবাশীষ ধরকে ফুল দিয়ে সম্মান জানাচ্ছেন শ্রীমতী রিঙ্কু মজুমদার ঘোষ।",
    clipCaption5: "বেদি থেকে বক্তব্য রাখছেন শ্রী দেবাশীষ ধর।",
    clipCaption6: "প্রশ্নোত্তর পর্বে মঞ্চের সামনে মাইক্রোফোন নিয়ে সমবেত সাংবাদিকেরা।",
    clipCaption7: "সাংবাদিকদের ভিড়ে প্রশ্নের উত্তর দিচ্ছেন শ্রী দেবাশীষ ধর।",
  },
};
